[tool.poetry]
name = "tg-bot-videos"
version = "0.1.0"
description = ""
authors = ["NazKar@Nazir <karimov.nazir00@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
flake8 = "^7.3.0"
isort = "^7.0.0"
black = "^25.12.0"
psycopg2-binary = "^2.9.11"
pydantic = "^2.12.5"
asyncpg = "^0.31.0"
openai = "^2.9.0"
python-dotenv = "^1.2.1"
aiogram = "^3.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
